PONTO.WEB/Models/ClienteViewsModel.cs
using PONTO.DOMAIN.Entidades;

namespace PONTO.WEB.Models
{
    public class ClienteViewsModel
    {
        public Cliente Cliente { get; set; }
        public List<Email>? Emails { get; set; }
        public List<Beneficios>? Beneficios { get; set; }
        public List<Contratacao>? Contratos { get; set; }
        public List<DisparosAcaoMkt>? DisparosAcaos { get; set; }
        public List<Emprestimo>? Emprestimos { get; set; }
        public List<Endereco>? Enderecos { get; set; }
        public List<Historico>? Historicos { get; set; }
        public List<ResultadoBot>? ResultadoBots { get; set; }
        public List<Telefone>? Telefones { get; set; }

    }
}

PONTO.WEB/Models/ErrorViewModel.cs
namespace PONTO.WEB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PONTO.WEB/Controllers/CadastroClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PONTO.DAO;
using PONTO.DOMAIN.Entidades;
using PONTO.WEB.Models;

namespace PONTO.WEB.Controllers
{
    public class CadastroClientesController : Controller
    {
        private readonly appDbContext _context;

        public CadastroClientesController(appDbContext context)
        {
            _context = context;
        }

        // GET: CadastroClientes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clientes.ToListAsync());
        }

        // GET: CadastroClientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ClienteViewsModel clienteViews = new ClienteViewsModel();


            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.IdCliente == id);


            if (cliente == null)
            {
                return NotFound();
            }

            clienteViews.Emails = _context.Emails.Where(a => a.CPF == cliente.CPF).ToList();
            clienteViews.Telefones = _context.Telefones.Where(a => a.CPF == cliente.CPF).ToList();
            clienteViews.Enderecos = _context.Enderecos.Where(a =>a.CPF == cliente.CPF).ToList();
            clienteViews.DisparosAcaos = _context.disparosAcaos.Where(a => a.CPF == cliente.CPF).ToList();
            clienteViews.ResultadoBots = _context.resultadoBots.Where(a => a.CPF == cliente.CPF).ToList();


            clienteViews.Cliente = cliente;




            return View(clienteViews);
        }

        // GET: CadastroClientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CadastroClientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCliente,Nome,CPF,RG,DataNascimento,Aposentado,NomeMae,NomePai,LocalNasc,StatusCad,DataCadastro")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: CadastroClientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ClienteViewsModel clienteViews = new ClienteViewsModel();

            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }

            clienteViews.Emails = _context.Emails.Where(a => a.CPF == cliente.CPF).ToList();
            clienteViews.Telefones = _context.Telefones.Where(a => a.CPF == cliente.CPF).ToList();
            clienteViews.Enderecos = _context.Enderecos.Where(a => a.CPF == cliente.CPF).ToList();
            clienteViews.DisparosAcaos = _context.disparosAcaos.Where(a => a.CPF == cliente.CPF).ToList();
            clienteViews.ResultadoBots = _context.resultadoBots.Where(a => a.CPF == cliente.CPF).ToList();


            clienteViews.Cliente = cliente;

            return View(clienteViews);
        }

        // POST: CadastroClientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("IdCliente,Nome,CPF,RG,DataNascimento,Aposentado,NomeMae,NomePai,LocalNasc,StatusCad,DataCadastro")] Cliente cliente)
        public async Task<IActionResult> Edit(int id, ClienteViewsModel DadosCliente)
        {
            if (id != DadosCliente.Cliente.IdCliente)
            {
                return NotFound();
            }

            if(DadosCliente.Emails != null)
            {
                try
                {
                    for (int i = 0; i < DadosCliente.Emails.Count; i++)
                    {
                        var email = _context.Emails.FirstOrDefault(e => e.IdEmail == DadosCliente.Emails[i].IdEmail);
                        if (email != null)
                        {
                            email.EmailCliente = DadosCliente.Emails[i].EmailCliente;
                        }
                        _context.Update(email);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (Exception)
                {

                }
            
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(DadosCliente.Cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(DadosCliente.Cliente.IdCliente))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(DadosCliente);
        }

        // GET: CadastroClientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.IdCliente == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: CadastroClientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente != null)
            {
                _context.Clientes.Remove(cliente);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
            return _context.Clientes.Any(e => e.IdCliente == id);
        }
    }
}

PONTO.WEB/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PONTO.WEB.Models;
using System.Diagnostics;

namespace PONTO.WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PONTO.WEB/Views/CadastroClientes/Create.cshtml
@model PONTO.DOMAIN.Entidades.Cliente

@{
    ViewData["Title"] = "Create";
}

<h1 class="my-4">Cadastrar Novo Cliente</h1>

<div class="card">
    <div class="card-body">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group mb-3">
                        <label asp-for="Nome" class="form-label"></label>
                        <input asp-for="Nome" class="form-control" />
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="CPF" class="form-label"></label>
                        <input asp-for="CPF" class="form-control" />
                        <span asp-validation-for="CPF" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="RG" class="form-label"></label>
                        <input asp-for="RG" class="form-control" />
                        <span asp-validation-for="RG" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label class="form-label">Data de Nascimento</label>
                        <input asp-for="DataNascimento" class="form-control" />
                        <span asp-validation-for="DataNascimento" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="Aposentado" class="form-label"></label>
                        <input asp-for="Aposentado" class="form-control" />
                        <span asp-validation-for="Aposentado" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group mb-3">
                        <label aclass="form-label">Nome da Mãe</label>
                        <input asp-for="NomeMae" class="form-control" />
                        <span asp-validation-for="NomeMae" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label class="form-label">Nome do Pai</label>
                        <input asp-for="NomePai" class="form-control" />
                        <span asp-validation-for="NomePai" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label class="form-label">Local de Nascimento</label>
                        <input asp-for="LocalNasc" class="form-control" />
                        <span asp-validation-for="LocalNasc" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label class="form-label">Status Cadastro</label>
                        <input asp-for="StatusCad" class="form-control" />
                        <span asp-validation-for="StatusCad" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="d-flex justify-content-end mt-4">
                <input type="submit" value="Cadastrar" class="btn btn-primary me-2" />
                <a asp-action="Index" class="btn btn-secondary">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

PONTO.WEB/Views/CadastroClientes/Delete.cshtml
@* @model PONTO.DOMAIN.Entidades.Cliente *@
@model PONTO.WEB.Models.ClienteViewsModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Deletar Cliente</h1>

<h3>Você deseja deletar esse cliente?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliente.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente.CPF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliente.CPF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente.RG)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliente.RG)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente.DataNascimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliente.DataNascimento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente.Aposentado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliente.Aposentado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente.NomeMae)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliente.NomeMae)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente.NomePai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliente.NomePai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente.LocalNasc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliente.LocalNasc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente.StatusCad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliente.StatusCad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente.DataCadastro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliente.DataCadastro)
        </dd>
    </dl>


    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Cliente.IdCliente" />
        <input type="submit" value="Deletar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

PONTO.WEB/Views/CadastroClientes/Details.cshtml
@* @model PONTO.DOMAIN.Entidades.Cliente *@
@model PONTO.WEB.Models.ClienteViewsModel

@{
    ViewData["Title"] = "Details";
}


<div class="card">
    <div class="card-header">
        <h4 class="card-title">Detalhes do Cliente</h4>
    </div>
    <div class="card-body">
        <dl class="row mb-0">
            <dt class="col-sm-3">@Html.DisplayNameFor(model => model.Cliente.Nome)</dt>
            <dd class="col-sm-9">@Html.DisplayFor(model => model.Cliente.Nome)</dd>

            <dt class="col-sm-3">@Html.DisplayNameFor(model => model.Cliente.CPF)</dt>
            <dd class="col-sm-9">@Html.DisplayFor(model => model.Cliente.CPF)</dd>

            <dt class="col-sm-3">@Html.DisplayNameFor(model => model.Cliente.RG)</dt>
            <dd class="col-sm-9">@Html.DisplayFor(model => model.Cliente.RG)</dd>

            <dt class="col-sm-3">Data de Nascimento</dt>
            <dd class="col-sm-9">@Html.DisplayFor(model => model.Cliente.DataNascimento)</dd>

            <dt class="col-sm-3">@Html.DisplayNameFor(model => model.Cliente.Aposentado)</dt>
            <dd class="col-sm-9">@Html.DisplayFor(model => model.Cliente.Aposentado)</dd>

            <dt class="col-sm-3">Nome da Mãe</dt>
            <dd class="col-sm-9">@Html.DisplayFor(model => model.Cliente.NomeMae)</dd>

            <dt class="col-sm-3">Nome do Pai</dt>
            <dd class="col-sm-9">@Html.DisplayFor(model => model.Cliente.NomePai)</dd>

            <dt class="col-sm-3">Local de Nascimento</dt>
            <dd class="col-sm-9">@Html.DisplayFor(model => model.Cliente.LocalNasc)</dd>

            <dt class="col-sm-3">Status Cadastro</dt>
            <dd class="col-sm-9">@Html.DisplayFor(model => model.Cliente.StatusCad)</dd>

            <dt class="col-sm-3">Data de Cadastro</dt>
            <dd class="col-sm-9">@Html.DisplayFor(model => model.Cliente.DataCadastro)</dd>
        </dl>
    </div>


    <div class="card-header">
        <h4 class="card-title">Contatos</h4>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-6">
                <h5>E-Mails</h5>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Email Cliente</th>
                            <th>Status</th>
                            <th>Score</th>
                            <th>Data Cad</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var email in Model.Emails)
                        {
                            <tr>
                                <td>@email.EmailCliente</td>
                                <td>@email.StatusEmail</td>
                                <td>@email.ScoreInterno</td>
                                <td>@email.DataCadastro</td>
                            </tr>
                        }
                        @if (!Model.Emails.Any())
                        {
                            <tr>
                                <td>Nenhum e-mail cadastrado.</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="col-sm-6">
                <h5>Telefones</h5>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Tipo Telefone</th>
                            <th>Telefone</th>
                            <th>Status</th>
                            <th>Score</th>
                            <th>Data Cad</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var telefone in Model.Telefones)
                        {
                            <tr>
                                <td>@telefone.TipoTelefone</td>
                                <td>(@telefone.DD)@telefone.NumTelefone</td>
                                <td>@telefone.StatusTelefone</td>
                                <td>@telefone.ScoreInterno</td>
                                <td>@telefone.DataCadastro</td>
                            </tr>
                        }
                        @if (!Model.Telefones.Any())
                        {
                            <tr>
                                <td>Nenhum telefone cadastrado.</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="card-header">
        <h4 class="card-title">Endereços</h4>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-10">
                <h5>Endereços do cliente</h5>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>UF</th>
                            <th>Cidade</th>
                            <th>Bairro</th>
                            <th>Rua</th>
                            <th>Cep</th>
                            <th>Número</th>
                            <th>Tipo</th>
                            <th>Status</th>
                            <th>Score</th>
                            <th>Data Cadastro</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var enderecos in Model.Enderecos)
                        {
                            <tr>
                                <td>@enderecos.Uf</td>
                                <td>@enderecos.Cidade</td>
                                <td>@enderecos.Bairro</td>
                                <td>@enderecos.Rua</td>
                                <td>@enderecos.Cep</td>
                                <td>@enderecos.Numero</td>
                                <td>@enderecos.Tipo</td>
                                <td>@enderecos.StatusEndereco</td>
                                <td>@enderecos.ScoreInterno</td>
                                <td>@enderecos.DataCadastro</td>
                            </tr>
                        }
                        @if (!Model.Emails.Any())
                        {
                            <tr>
                                <td>Nenhum e-mail cadastrado.</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>


    <div class="card-header">
        <h4 class="card-title">Ações de Contato</h4>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-10">
                <h5>Disparos de E-Mails e SMS</h5>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Canal de Envio</th>
                            <th>Email</th>
                            <th>Telefone</th>
                            <th>Nome do Mailing</th>
                            <th>Status Envio</th>
                            <th>Data Envio</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var acaomkt in Model.DisparosAcaos)
                        {
                            <tr>
                                <td>@acaomkt.CanalEnvio</td>
                                <td>@acaomkt.Email</td>
                                <td>@acaomkt.Telefone</td>
                                <td>@acaomkt.NomeMailing</td>
                                <td>@acaomkt.StatusEnvio</td>
                                <td>@acaomkt.DataEnvio</td>
                            </tr>
                        }
                        @if (!Model.Emails.Any())
                        {
                            <tr>
                                <td>Nenhum e-mail cadastrado.</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="card-header">
        <h4 class="card-title">Resultado Bot Sefaz</h4>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-10">
                <h5>Retorno de pesquisa do robô</h5>
                <table class="table table-bordered table-responsive" style="overflow-x: auto;".;lç>
                    <thead>
                        <tr>
                            <th>ORGÃO</th>
                            <th>TPVINCULO</th>
                            <th>MBCONSIFACULTA</th>
                            <th>MBCARTAOCREDITO</th>
                            <th>MBCARTAOBENEF</th>
                            <th>MDCONSIFACULTA</th>
                            <th>MDCARTAOCREDITO</th>
                            <th>MDCARTAOBENEF</th>
                            <th>NUM_MATRICULA</th>
                            <th>QTD_NUM_MAT</th>
                            @* <th>MARGEM_5</th>
                            <th>RESULTADO</th>
                            <th>MENSAGEM_CONSIGNADO</th>
                            <th>MENSAGEM_CARTAO_CREDITO</th> *@
                            <th>DataConsulta</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var bost in Model.ResultadoBots)
                        {
                            <tr>
                                <td>@bost.ORGAO</td>
                                <td>@bost.TPVINCULO</td>
                                <td>@bost.MBCONSIFACULTA</td>
                                <td>@bost.MBCARTAOCREDITO</td>
                                <td>@bost.MBCARTAOBENEF</td>
                                <td>@bost.MDCONSIFACULTA</td>
                                <td>@bost.MDCARTAOCREDITO</td>
                                <td>@bost.MDCARTAOBENEF</td>
                                <td>@bost.NUM_MATRICULA</td>
                                <td>@bost.QTD_NUM_MAT</td>
                                @* <td>@bost.MARGEM_5</td>
                                <td>@bost.RESULTADO</td>
                                <td>@bost.MENSAGEM_CONSIGNADO</td>
                                <td>@bost.MENSAGEM_CARTAO_CREDITO</td> *@
                                <td>@bost.DataConsulta</td>
                            </tr>
                        }
                        @if (!Model.Emails.Any())
                        {
                            <tr>
                                <td>Nenhum e-mail cadastrado.</td>
                            </tr>
                        }
                    </tbody>
                </table>
            
            </div>
        </div>
    </div>


    <div class="card-footer text-end">
        <a asp-action="Edit" asp-route-id="@Model?Cliente.IdCliente" class="btn btn-primary me-2">Editar</a>
        <a asp-action="Index" class="btn btn-secondary">Voltar</a>
    </div>
</div>

PONTO.WEB/Views/Shared/_Layout - Cópia.cshtml
   <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PONTO.WEB</title>
    <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />-->
    <link rel="stylesheet" href="~/adminlte/dist/css/adminlte.min.css"/>

    <link rel="stylesheet" href="~/adminlte/dist/css/adminlte.css" />
    <link rel="stylesheet" href="~/adminlte/dist/css/adminlte.css.map" />
    <link rel="stylesheet" href="~/adminlte/dist/css/adminlte.rtl.css.map" />
    <link rel="stylesheet" href="~/adminlte/dist/js/adminlte.js" />

   @*  <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PONTO.WEB.styles.css" asp-append-version="true" /> *@

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&amp;display=fallback">
    <link rel="stylesheet" href="~/adminlte/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" href="~/adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/bs-stepper/css/bs-stepper.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/dropzone/min/dropzone.min.css">
    <link rel="stylesheet" href="~/adminlte/dist/css/adminlte.min.css?v=3.2.0">
    <script src="chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/prompt.js"></script>


</head>



<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PONTO.WEB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CadastroClientes" asp-action="Index">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>




    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PONTO.WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
@*     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
@*     <script src="~/js/site.js" asp-append-version="true"></script> *@
    <script src="~/adminlte/dist/js/adminlte.js" asp-append-version="true"></script>

    <script src="~/adminlte/plugins/jquery/jquery.min.js"></script>
    <script src="~/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/adminlte/plugins/select2/js/select2.full.min.js"></script>
    <script src="~/adminlte/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js"></script>
    <script src="~/adminlte/plugins/moment/moment.min.js"></script>
    <script src="~/adminlte/plugins/inputmask/jquery.inputmask.min.js"></script>
    <script src="~/adminlte//plugins/daterangepicker/daterangepicker.js"></script>
    <script src="~/adminlte/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>
    <script src="~/adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="~/adminlte/plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>
    <script src="~/adminlte/plugins/bs-stepper/js/bs-stepper.min.js"></script>
    <script src="~/adminlte/plugins/dropzone/min/dropzone.min.js"></script>
    <script src="~/adminlte/dist/js/adminlte.js"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>